version: "3.1"
services:
    message_broker:
        image: eclipse-mosquitto
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

    videos:
        image: halverneus/static-file-server
        ports:
            - 8081:8080
        volumes:
            - "./videos/:/web/videos/"
