version: "3.7"
services:
    qr:
        image: nimashoghi/v2v-qr
        environment:
            IP_ADDRESS: 0
            VIDEO_INPUT: 0
    client:
        image: nimashoghi/dac-v2v:latest
        ports:
            - "8080:8080"
        environment:
            SOCKET_SERVER_PORT: "8080"
            MQTT_HOST: "mqtt://192.168.0.120"
            MY_TOPIC: "${CLIENT_ID}"
            ALL_TOPICS: "0,1"
            PRIVATE_KEY_LOCATION: "/app/keys/private.pem"
            PUBLIC_KEY_LOCATION: "/app/keys/public.pem"
        volumes:
            - "../../keys/${CLIENT_ID}/:/app/keys/"
